name: Some actions/checks before merge to master

on:
  pull_request:
  merge_group:

jobs:
  merge-pr:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: Run 1 min sleep
      run: sleep 30
